# Generated by Django 4.1.5 on 2024-01-08 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockdataquarter',
            old_name='DebtRatio',
            new_name='debt_ratio',
        ),
        migrations.RenameField(
            model_name='stockdataquarter',
            old_name='DividendPropensity',
            new_name='dividend_propensity',
        ),
        migrations.RenameField(
            model_name='stockdataquarter',
            old_name='DividendYield',
            new_name='dividend_yield',
        ),
        migrations.RenameField(
            model_name='stockdataquarter',
            old_name='PBR',
            new_name='pbr',
        ),
        migrations.RenameField(
            model_name='stockdataquarter',
            old_name='PER',
            new_name='per',
        ),
        migrations.RenameField(
            model_name='stockdataquarter',
            old_name='ROE',
            new_name='roe',
        ),
        migrations.RenameField(
            model_name='stockdatayear',
            old_name='DebtRatio',
            new_name='debt_ratio',
        ),
        migrations.RenameField(
            model_name='stockdatayear',
            old_name='DividendPropensity',
            new_name='dividend_propensity',
        ),
        migrations.RenameField(
            model_name='stockdatayear',
            old_name='DividendYield',
            new_name='dividend_yield',
        ),
        migrations.RenameField(
            model_name='stockdatayear',
            old_name='PBR',
            new_name='pbr',
        ),
        migrations.RenameField(
            model_name='stockdatayear',
            old_name='PER',
            new_name='per',
        ),
        migrations.RenameField(
            model_name='stockdatayear',
            old_name='ROE',
            new_name='roe',
        ),
    ]
