# Generated by Django 4.1.5 on 2024-01-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystock', '0002_rename_debtratio_stockdataquarter_debt_ratio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='stockdataquarter',
            old_name='period',
            new_name='quarter',
        ),
        migrations.RenameField(
            model_name='stockdatayear',
            old_name='period',
            new_name='year',
        ),
    ]
